# This is a basic workflow to help you get started with Actions

name: bulid

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: publish
        env:
            BUILD_CONFIG: ${{ secrets.BUILD_CONFIG }}
        run: |
          echo "安装依赖"
          sudo apt update
          sudo pip3 install setuptools
          sudo pip3 install -r requirements.txt
          echo "开始生成静态网页"
          sphinx-build -b html ./source ./build -E
          echo "生成静态网页完成"
          echo "发布到服务器"
          curl https://dl.minio.org.cn/client/mc/release/linux-amd64/mc --create-dirs -o $HOME/minio-binaries/mc
          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/
          mc alias set myminio $BUILD_CONFIG
          mc cp --recursive ./build myminio/web/main
          echo "发布完成"



      # 打包build文件夹
      - name: Archive production artifacts
        run: |
          echo "打包build文件夹"
          tar -zcvf build.tar.gz build
          echo "打包完成"

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar.gz          



